public class ReleasePokemon {
    /*
    @auraEnabled
    public static List<Pokemon_Roster__c> getRosterSlot(){    
    		return [Select Name From Pokemon_Roster__c];    
}
    @AuraEnabled
	public static void deletePokemonSlot(Pokemon_Roster__c toDelete){
    		delete toDelete;
}
    
    /*static public void DeleteThePokemon(Id PokemonRosterId){
        Delete [Select Id from Pokemon_Roster__c where Id=:PokemonRosterID]; 
    }*/

}